[% INCLUDE fvl.inc %]
<div class="section">
<label for="title">プロジェクト名（必須）</label>
<input type="text" name="title" value="" class="check" />
<p class="ex">例）プロジェクトＡ</p>
</div><!-- /section -->

<div class="section">
<label for="description">説明<span>livedoor Wiki記法も使えるよ！</span></label>
<textarea name="description"></textarea>
<p class="ex">例）ジャッキーチェン主演のアクション超大作！</p>
</div><!-- /section -->

<div class="button"><input type="submit" value="プロジェクトの記録を開始！" /></div>
