<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" lang="ja">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf8" />
<title></title>
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<link rel="home" href="" title="" />
<link rel="help" href="" title="" />
<link rel="icon" type="image/x-icon" href="/img/favicon.ico" />
<link rel="Shortcut Icon" type="img/x-icon" href="/img/favicon.ico" />
<link rel="stylesheet" type="text/css" href="/static/css/style.css" />
<script type="text/javascript" src=""></script>

</head>
<body>
<div id="header">
<div id="container">
[% IF c.req.user %]
<div id="login"><span>[% c.req.user %]ちゃん</span></div>
[% ELSE %]
<div id="login"><a href="/cms/">ログイン</a></div>
[% END %]
<div id="header">
<div id="site-title">
<h1>プロジェクト見守るくん（仮）</h1>
<p>プロジェクトの歴史的経緯を記録していくこころみだよー。</p>
</div><!-- /site-title -->
</div><!-- /header -->
